Repository Ttottoga/BE, pull requests merged in 2024-02, with the labels that each got.

#29 Feature/24 register review
  src/main/java/com/umc/ttg/domain/member/exception/exception.java
  src/main/java/com/umc/ttg/domain/member/exception/handler/MemberHandler.java
  src/main/java/com/umc/ttg/domain/review/api/ReviewController.java
  src/main/java/com/umc/ttg/domain/review/api/api.java
  src/main/java/com/umc/ttg/domain/review/application/ReviewCommandService.java
  src/main/java/com/umc/ttg/domain/review/application/ReviewCommandServiceImpl.java
  src/main/java/com/umc/ttg/domain/review/application/application.java
  src/main/java/com/umc/ttg/domain/review/dto/ReviewRegisterRequestDTO.java
  src/main/java/com/umc/ttg/domain/review/dto/ReviewRegisterResponseDTO.java
  src/main/java/com/umc/ttg/domain/review/dto/dto.java
  src/main/java/com/umc/ttg/domain/review/entity/Review.java
  src/main/java/com/umc/ttg/domain/review/exception/exception.java
  src/main/java/com/umc/ttg/domain/review/repository/ReviewRepository.java
  src/main/java/com/umc/ttg/domain/review/repository/repository.java
Labels: :sparkles: feature

#25 Feature/23 find coupon Details
  .gitignore
  src/main/java/com/umc/ttg/domain/coupon/api/CouponController.java
  src/main/java/com/umc/ttg/domain/coupon/application/CouponService.java
  src/main/java/com/umc/ttg/domain/coupon/application/CouponServiceImpl.java
  src/main/java/com/umc/ttg/domain/coupon/repository/CouponRepository.java
  src/main/java/com/umc/ttg/global/common/ResponseCode.java
Labels: :sparkles: feature

#40 Feature/38 s3 link
  .gitignore
  build.gradle
  src/main/java/com/umc/ttg/domain/store/api/StoreController.java
  src/main/java/com/umc/ttg/domain/store/application/StoreCommandService.java
  src/main/java/com/umc/ttg/domain/store/application/StoreCommandServiceImpl.java
  src/main/java/com/umc/ttg/domain/store/dto/converter/StoreConverter.java
  src/main/java/com/umc/ttg/domain/store/entity/Store.java
  src/main/java/com/umc/ttg/global/common/AwsS3.java
  src/main/java/com/umc/ttg/global/common/ResponseCode.java
  src/main/java/com/umc/ttg/global/config/AwsS3Config.java
  src/main/java/com/umc/ttg/global/config/config.java
  src/main/java/com/umc/ttg/global/error/handler/AwsS3Handler.java
  src/main/java/com/umc/ttg/global/util/AwsS3Service.java
  src/main/resources/application.properties
Labels: :sparkles: feature, :recycle: refactor

#34 Feature/28 find stores by region
  src/main/java/com/umc/ttg/domain/member/entity/HeartStore.java
  src/main/java/com/umc/ttg/domain/member/entity/Member.java
  src/main/java/com/umc/ttg/domain/member/repository/HeartStoreRepository.java
  src/main/java/com/umc/ttg/domain/store/api/StoreController.java
  src/main/java/com/umc/ttg/domain/store/application/StoreCommandService.java
  src/main/java/com/umc/ttg/domain/store/application/StoreCommandServiceImpl.java
  src/main/java/com/umc/ttg/domain/store/dto/StoreCreateRequestDto.java
  src/main/java/com/umc/ttg/domain/store/dto/StoreFindByRegionResponseDto.java
  src/main/java/com/umc/ttg/domain/store/repository/StoreRepository.java
Labels: :sparkles: feature

#39 Feature/37 QrCode
  build.gradle
  src/main/java/com/umc/ttg/domain/coupon/api/CouponController.java
  src/main/java/com/umc/ttg/domain/coupon/application/CouponService.java
  src/main/java/com/umc/ttg/domain/coupon/application/CouponServiceImpl.java
  src/main/java/com/umc/ttg/domain/coupon/utils/QrCodeGenerator.java
Labels: :sparkles: feature

#27 Feature/22 home
  src/main/java/com/umc/ttg/domain/review/repository/ReviewRepository.java
  src/main/java/com/umc/ttg/domain/store/api/StoreController.java
  src/main/java/com/umc/ttg/domain/store/application/StoreCommandService.java
  src/main/java/com/umc/ttg/domain/store/application/StoreCommandServiceImpl.java
  src/main/java/com/umc/ttg/domain/store/dto/HomeResponseDto.java
  src/main/java/com/umc/ttg/domain/store/dto/StoreFindByMenuResponseDto.java
  src/main/java/com/umc/ttg/domain/store/dto/StoreFindResponseDto.java
  src/main/java/com/umc/ttg/domain/store/dto/converter/StoreConverter.java
  src/main/java/com/umc/ttg/domain/store/entity/Store.java
  src/main/java/com/umc/ttg/domain/store/repository/StoreRepository.java
Labels: :sparkles: feature

#36 Feature/30 feature look up my page
  src/main/java/com/umc/ttg/domain/coupon/dto/MyPageCouponResponseDTO.java
  src/main/java/com/umc/ttg/domain/coupon/dto/converter/CouponConverter.java
  src/main/java/com/umc/ttg/domain/coupon/repository/CouponRepository.java
  src/main/java/com/umc/ttg/domain/member/api/MemberController.java
  src/main/java/com/umc/ttg/domain/member/api/api.java
  src/main/java/com/umc/ttg/domain/member/application/MemberQueryService.java
  src/main/java/com/umc/ttg/domain/member/application/MemberQueryServiceImpl.java
  src/main/java/com/umc/ttg/domain/member/application/application.java
  src/main/java/com/umc/ttg/domain/member/dto/MyPageAllResponseDto.java
  src/main/java/com/umc/ttg/domain/member/dto/MyPageMemberResponseDTO.java
  src/main/java/com/umc/ttg/domain/member/dto/converter/MemberConverter.java
  src/main/java/com/umc/ttg/domain/member/dto/dto.java
  src/main/java/com/umc/ttg/domain/review/dto/MyPageReviewResponseDTO.java
  src/main/java/com/umc/ttg/domain/review/dto/ReviewRegisterRequestDTO.java
  src/main/java/com/umc/ttg/domain/review/repository/ReviewRepository.java
  src/main/java/com/umc/ttg/domain/store/dto/MyPageStoreResponseDto.java
  src/main/java/com/umc/ttg/domain/store/dto/converter/StoreConverter.java
  src/main/java/com/umc/ttg/global/common/ResponseCode.java
Labels: :sparkles: feature

#49 Feature/46 search store
  src/main/java/com/umc/ttg/domain/store/api/StoreController.java
  src/main/java/com/umc/ttg/domain/store/application/StoreCommandService.java
  src/main/java/com/umc/ttg/domain/store/application/StoreCommandServiceImpl.java
  src/main/java/com/umc/ttg/domain/store/dto/StoreSearchResponseDto.java
  src/main/java/com/umc/ttg/domain/store/repository/StoreRepository.java
  src/main/java/com/umc/ttg/global/common/ResponseCode.java
Labels: :sparkles: feature

#51 Feature/50 modify a profile image
  src/main/java/com/umc/ttg/domain/member/api/MemberController.java
  src/main/java/com/umc/ttg/domain/member/application/MemberCommandService.java
  src/main/java/com/umc/ttg/domain/member/application/MemberCommandServiceImpl.java
  src/main/java/com/umc/ttg/domain/member/dto/MemberImageRequestDTO.java
  src/main/java/com/umc/ttg/domain/member/dto/MemberImageResponseDTO.java
  src/main/java/com/umc/ttg/domain/member/entity/Member.java
  src/main/java/com/umc/ttg/domain/review/application/ReviewCommandServiceImpl.java
  src/main/java/com/umc/ttg/global/common/ResponseCode.java
Labels: :sparkles: feature

#44 Feature/43 upload Qrcode
  build.gradle
  src/main/java/com/umc/ttg/domain/coupon/application/CouponServiceImpl.java
  src/main/java/com/umc/ttg/domain/coupon/dto/CouponResponseDto.java
  src/main/java/com/umc/ttg/domain/coupon/entity/Coupon.java
  src/main/java/com/umc/ttg/domain/coupon/utils/BitMatrixToMultipartFileConverter.java
  src/main/java/com/umc/ttg/domain/coupon/utils/CustomMultipartFile.java
  src/main/java/com/umc/ttg/domain/coupon/utils/QrCodeGenerator.java
  src/main/java/com/umc/ttg/domain/review/api/ReviewController.java
  src/main/java/com/umc/ttg/domain/review/application/ReviewCommandService.java
  src/main/java/com/umc/ttg/domain/review/application/ReviewCommandServiceImpl.java
Labels: :sparkles: feature

#53 Feature/52 heart store
  src/main/java/com/umc/ttg/domain/member/entity/HeartStore.java
  src/main/java/com/umc/ttg/domain/store/api/StoreController.java
  src/main/java/com/umc/ttg/domain/store/application/StoreCommandService.java
  src/main/java/com/umc/ttg/domain/store/application/StoreCommandServiceImpl.java
  src/main/java/com/umc/ttg/domain/store/dto/HeartStoreResponseDto.java
  src/main/java/com/umc/ttg/global/common/ResponseCode.java
Labels: :sparkles: feature

#55 :sparkles: Update Store
  src/main/java/com/umc/ttg/domain/store/api/StoreController.java
  src/main/java/com/umc/ttg/domain/store/application/StoreCommandService.java
  src/main/java/com/umc/ttg/domain/store/application/StoreCommandServiceImpl.java
  src/main/java/com/umc/ttg/domain/store/dto/StoreRequestDto.java
  src/main/java/com/umc/ttg/domain/store/dto/StoreResponseDto.java
  src/main/java/com/umc/ttg/domain/store/dto/converter/StoreConverter.java
  src/main/java/com/umc/ttg/domain/store/entity/Store.java
  src/main/java/com/umc/ttg/domain/store/repository/RegionRepository.java
Labels: :sparkles: feature

#58 feature/57-use-coupon
  src/main/java/com/umc/ttg/domain/coupon/api/CouponController.java
  src/main/java/com/umc/ttg/domain/coupon/application/CouponService.java
  src/main/java/com/umc/ttg/domain/coupon/application/CouponServiceImpl.java
  src/main/java/com/umc/ttg/domain/coupon/dto/converter/CouponConverter.java
  src/main/java/com/umc/ttg/domain/coupon/entity/Coupon.java
Labels: :sparkles: feature

#65 :sparkles: RDS 연결
  build.gradle
  src/main/resources/application.properties
Labels: :sparkles: feature

#74 Feature/48 refactor store related features
  src/main/java/com/umc/ttg/domain/member/application/MemberService.java
  src/main/java/com/umc/ttg/domain/member/application/MemberServiceImpl.java
  src/main/java/com/umc/ttg/domain/store/api/StoreController.java
  src/main/java/com/umc/ttg/domain/store/application/StoreQueryService.java
  src/main/java/com/umc/ttg/domain/store/application/StoreQueryServiceImpl.java
  src/main/java/com/umc/ttg/global/auth/WebSecurityConfiguration.java
  src/main/java/com/umc/ttg/global/common/ResponseCode.java
  src/main/resources/application-h2.properties
Labels: :recycle: refactor

#76 Fix/71 validate member coupon
  src/main/java/com/umc/ttg/domain/coupon/api/CouponController.java
  src/main/java/com/umc/ttg/domain/coupon/application/CouponService.java
  src/main/java/com/umc/ttg/domain/coupon/application/CouponServiceImpl.java
Labels: 🔧 fix

#88 Fix: 멤버 토큰 수정
  src/main/java/com/umc/ttg/domain/member/api/MemberController.java
  src/main/java/com/umc/ttg/domain/member/application/MemberCommandService.java
  src/main/java/com/umc/ttg/domain/member/application/MemberCommandServiceImpl.java
  src/main/java/com/umc/ttg/domain/member/application/MemberQueryService.java
  src/main/java/com/umc/ttg/domain/member/application/MemberQueryServiceImpl.java
  src/main/java/com/umc/ttg/domain/review/api/ReviewController.java
  src/main/java/com/umc/ttg/domain/review/application/ReviewCommandService.java
  src/main/java/com/umc/ttg/domain/review/application/ReviewCommandServiceImpl.java
  src/main/java/com/umc/ttg/domain/review/repository/ReviewRepository.java
  src/main/java/com/umc/ttg/domain/store/api/StoreController.java
  src/main/java/com/umc/ttg/domain/store/application/StoreCommandService.java
  src/main/java/com/umc/ttg/domain/store/application/StoreCommandServiceImpl.java
  src/main/java/com/umc/ttg/domain/store/dto/HeartStoreResponseDto.java
Labels: 🔧 fix

#92 Fix: 리뷰 예외 추가, 리뷰가 중복된 상태에서 마이페이지 조회 시 쿠폰이 제대로 받지 않는 오류 해결
  src/main/java/com/umc/ttg/domain/coupon/repository/CouponRepository.java
  src/main/java/com/umc/ttg/domain/member/application/MemberQueryServiceImpl.java
  src/main/java/com/umc/ttg/domain/review/application/ReviewCommandServiceImpl.java
  src/main/java/com/umc/ttg/domain/review/dto/MyPageReviewResponseDTO.java
  src/main/java/com/umc/ttg/domain/review/exception/handler/ReviewHandler.java
  src/main/java/com/umc/ttg/domain/review/repository/ReviewRepository.java
  src/main/java/com/umc/ttg/domain/store/dto/converter/StoreConverter.java
  src/main/java/com/umc/ttg/global/common/ResponseCode.java
Labels: :bug: bug

#91 fix/89 add review count
  src/main/java/com/umc/ttg/domain/coupon/api/CouponController.java
  src/main/java/com/umc/ttg/domain/coupon/application/CouponService.java
  src/main/java/com/umc/ttg/domain/coupon/application/CouponServiceImpl.java
  src/main/java/com/umc/ttg/domain/member/application/MemberService.java
  src/main/java/com/umc/ttg/domain/member/application/MemberServiceImpl.java
  src/main/java/com/umc/ttg/domain/member/entity/Member.java
  src/main/java/com/umc/ttg/domain/review/application/ReviewCommandServiceImpl.java
  src/main/java/com/umc/ttg/domain/store/entity/Store.java
Labels: 🔧 fix

#94 Fix: 마이페이지 멤버 DTO 수정
  src/main/java/com/umc/ttg/domain/member/dto/MyPageMemberResponseDTO.java
  src/main/java/com/umc/ttg/domain/member/dto/converter/MemberConverter.java
Labels: 🔧 fix

#96 Fix: 마이페이지(이미지 변경) DTO 변경
  src/main/java/com/umc/ttg/domain/member/application/MemberCommandServiceImpl.java
  src/main/java/com/umc/ttg/domain/member/dto/MemberImageResponseDTO.java
Labels: 🔧 fix

#97 Feature/48 refactor store related features
  src/main/java/com/umc/ttg/domain/store/application/StoreCommandServiceImpl.java
  src/main/java/com/umc/ttg/domain/store/dto/converter/StoreConverter.java
Labels: :recycle: refactor
